// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6qzX3pjR9XZZCSjvCiquogtjTBFWjbc4',
    appId: '1:495791136012:web:5583767dcebe3910ebfd29',
    messagingSenderId: '495791136012',
    projectId: 'hihear-6d7d5',
    authDomain: 'hihear-6d7d5.firebaseapp.com',
    storageBucket: 'hihear-6d7d5.firebasestorage.app',
    measurementId: 'G-QETXY6K2ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Gn1MKZL_cp1mvmsStbHKZRRZVDOtzDI',
    appId: '1:495791136012:android:be3e08c2351c1047ebfd29',
    messagingSenderId: '495791136012',
    projectId: 'hihear-6d7d5',
    storageBucket: 'hihear-6d7d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqmdNFYLegOV8c98kB_3OcJVD7D9MjyOs',
    appId: '1:495791136012:ios:a8d92541fb534ef8ebfd29',
    messagingSenderId: '495791136012',
    projectId: 'hihear-6d7d5',
    storageBucket: 'hihear-6d7d5.firebasestorage.app',
    iosClientId: '495791136012-q3c1iuic0e8hl22tm6b1sk0k541773cr.apps.googleusercontent.com',
    iosBundleId: 'com.example.hihearMo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqmdNFYLegOV8c98kB_3OcJVD7D9MjyOs',
    appId: '1:495791136012:ios:a8d92541fb534ef8ebfd29',
    messagingSenderId: '495791136012',
    projectId: 'hihear-6d7d5',
    storageBucket: 'hihear-6d7d5.firebasestorage.app',
    iosClientId: '495791136012-q3c1iuic0e8hl22tm6b1sk0k541773cr.apps.googleusercontent.com',
    iosBundleId: 'com.example.hihearMo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6qzX3pjR9XZZCSjvCiquogtjTBFWjbc4',
    appId: '1:495791136012:web:08585bd020bb510debfd29',
    messagingSenderId: '495791136012',
    projectId: 'hihear-6d7d5',
    authDomain: 'hihear-6d7d5.firebaseapp.com',
    storageBucket: 'hihear-6d7d5.firebasestorage.app',
    measurementId: 'G-BZCETZB5DC',
  );
}
